CC = gcc
CFLAGS = -c -std=c99 -g
LDFLAGS = -g
SRC = $(wildcard src/*.c)
HDR = $(wildcard src/*.h)
OBJ = $(SRC:.c=.o)
EXEC = melody

all: $(src) $(OBJ) $(EXEC)

$(EXEC): $(OBJ)
	$(CC) $(LDFLAGS) $^ -o $@

%.o: %.c $(HDR)
	${CC} ${CFLAGS} $< -o $@

clean:
	del $(OBJ_DIR)\*.exe $(EXEC)
